// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IExternalAuthorsFields {
  /** ID */
  id?: string | undefined;

  /** Basic Data */
  separatorBasicData?: Document | undefined;

  /** First Name */
  firstName?: string | undefined;

  /** Last Name */
  lastName?: string | undefined;

  /** Email */
  email?: string | undefined;

  /** ORCID */
  orcid?: string | undefined;

  /** Teams */
  teams?: ITeams[] | undefined;

  /** Labs */
  labs?: ILabs[] | undefined;
}

export interface IExternalAuthors extends Entry<IExternalAuthorsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'externalAuthors';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ILabsFields {
  /** ID */
  id?: string | undefined;

  /** Name */
  name?: string | undefined;
}

export interface ILabs extends Entry<ILabsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'labs';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ISharedOutputsFields {
  /** ID */
  id?: string | undefined;

  /** Labs */
  labs?: ILabs[] | undefined;

  /** Authors */
  authors?: (IExternalAuthors | IUsers)[] | undefined;

  /** Title */
  title?: string | undefined;

  /** description */
  description?: Document | undefined;
}

export interface ISharedOutputs extends Entry<ISharedOutputsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'sharedOutputs';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ITeamsFields {
  /** ID */
  id?: string | undefined;

  /** Display Name */
  displayName?: string | undefined;

  /** Shared Outputs */
  outputs?: ISharedOutputs[] | undefined;
}

export interface ITeams extends Entry<ITeamsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'teams';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUsersFields {
  /** ID */
  id?: string | undefined;

  /** Basic Data */
  separatorBasicData?: Document | undefined;

  /** First Name */
  firstName?: string | undefined;

  /** Last Name */
  lastName?: string | undefined;

  /** Email */
  email?: string | undefined;

  /** ORCID */
  orcid?: string | undefined;

  /** Teams */
  teams?: ITeams[] | undefined;

  /** Labs */
  labs?: ILabs[] | undefined;
}

export interface IUsers extends Entry<IUsersFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'users';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE =
  | 'externalAuthors'
  | 'labs'
  | 'sharedOutputs'
  | 'teams'
  | 'users';

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
