name: Build Pipeline

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:16
#      credentials:
#        username: AWS
#        password: ${{ secrets.AWS_ECR_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          NODE_ENV: 'production'
        run: |
          source ci/env-setup.sh
          yarn build
