name: Setup

on:
  workflow_call:
    outputs:
      pr-number:
        description: "The current PR number"
        value: ${{ github.event.number || github.event.inputs.prNumber }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        id: build-step
        run: |
          echo "::set-output name=pr-number::$PR_NUMBER"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Image Name
        uses: ./.github/actions/ecr-registry
        id: image-name
